spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allow-credentials: true
            allowedHeaders: "*"
            allowedOrigins: "*"
            allowedMethods:
              - OPTIONS
              - GET
              - POST
              - PUT
              - DELETE
            max-age: 3600
      discovery:
        locator:
          #使用小写服务名，默认是大写
          lower-case-service-id: true
          #开启从注册中心动态创建路由的功能，利用微服务名进行路由
          enabled: true